### ISSUE TITLE
No connection could be made

### ISSUE THREAD

**Issue by Zwork101** [YegorDia/Steam-Trade-Bot#1]
After downloading Python2.7 JUST to use this program (I usually use python3.6). And filling out the information in `test_bot.py` I was annoyed to see this message:
```
Traceback (most recent call last):
  File "C:\Users\Zwork101\Desktop\PyBot\Steam-Trade-Bot-master\test_bot.py", line 11, in <module>
    bot = SteamBot(test_info["username"], email=test_info["email"], email_password=test_info["email_password"])
  File "C:\Users\Zwork101\Desktop\PyBot\Steam-Trade-Bot-master\steam_bot.py", line 222, in __init__
    self.email_reader = EmailReader(self.email, self._email_password)
  File "C:\Users\Zwork101\Desktop\PyBot\Steam-Trade-Bot-master\email_reader.py", line 32, in __init__
    self.connect()
  File "C:\Users\Zwork101\Desktop\PyBot\Steam-Trade-Bot-master\email_reader.py", line 36, in connect
    self.imap_conn = imaplib.IMAP4_SSL(self.imap_server)
  File "C:\Python27\lib\imaplib.py", line 1166, in __init__
    IMAP4.__init__(self, host, port)
  File "C:\Python27\lib\imaplib.py", line 173, in __init__
    self.open(host, port)
  File "C:\Python27\lib\imaplib.py", line 1177, in open
    self.sock = socket.create_connection((host, port))
  File "C:\Python27\lib\socket.py", line 575, in create_connection
    raise err
error: [Errno 10061] No connection could be made because the target machine actively refused it
```
Do I need to run it as an admin? Change some setting? I don't know why this is happening.

**Comment by YegorDia** [comment]
Maybe it just couldnt connect to mail server. If you have all premade data such as shared secret etc. You can run bot with this data properly this way:

```
username = ''
password = ''
device_id = ''
shared_secret = ''
identity_secret = ''

bot = SteamBot(username)
bot._cache_param("shared_secret", shared_secret)
bot._cache_param("identity_secret", identity_secret)
bot._cache_param("device_id", device_id)

def login():
    return bot.mobile_login(password)

```

**Comment by Zwork101** [comment]
Sorry for being rude about the problem I had, I'm not sure why I was so frustrated. Amazing bot!
